### ISSUE TITLE
Best Practice for big taxonSelectors

### ISSUE THREAD

**Issue by BugwoodCenter** [gimmefreshdata/freshdata#76] opened 2017-09-28 19:23 UTC
I have many taxa that i would like to pull data for.  They unfortunately do not share a common ancestor.  Is there a max number of taxa that I should consider limiting my requests to or another way that i should reference the list of taxa?

**Comment by jhammock** [comment] 2017-09-28 19:29
No maximum number of taxa that I know of. @jhpoelen may know better.

You can also leave that filter empty and take all taxa, if your workflow would rather filter for those taxa after download

**Comment by BugwoodCenter** [comment] 2017-09-28 19:37
Almost 4k taxa - I'll take a look at the volume of unfiltered.  I'd run into a limit on what a GET request can do and even on a rotation of a few taxa at a time would take a LONG time.  After we populate with the existing data, getting updates should be much lighter.  Never a good thing to bombard folks that share data :)

**Comment by diatomsRcool** [comment] 2017-09-28 20:57
If leaving out the limit doesn't work for you, I've been setting the 
number really high, like 5 million.

**Comment by jhpoelen** [comment] 2017-09-29 16:57
If I understand it correctly @BugwoodCenter is referring to the number of taxa in a checklist request and  @diatomsRcool is referring to limiting the length of the resulting checklist. 

number of taxa in checklist request - the number of taxa is restricted by the maximum allowable url length. This is because the current api puts the request in the url (e.g., http://[...]/?taxonSelector=Aves&...). It seems that might not work well for your use case, because you are requesting a taxonSelector that includes 4k taxa. 

~~Following https://github.com/jhpoelen/effechecka/issues/66 the max method length increased to 2147483647 in June 2017. However,~~ (see https://github.com/gimmefreshdata/freshdata/issues/76#issuecomment-333184769) 

Some software (incl. browsers) do not like/support very long urls: in case of extremely long requests, a post request with request in the content request body is preferred.

If needed, we can add a api endpoint to support such a post request - this way, you'd be able to ```upload``` a request like : 

```json
{
  "selector": {
    "taxonSelector": "taxon1|taxon2|taxon3|...|taxon4000",
    "wktString": "POLYGON ((-72.147216796875 41.492120839687786, -72.147216796875 43.11702412135048, -69.949951171875 43.11702412135048, -69.949951171875 41.492120839687786, -72.147216796875 41.492120839687786))",
    "traitSelector": ""
  }
}
```

@diatomsRcool @jhammock @BugwoodCenter curious to hear your thoughts on this...

**Comment by jhpoelen** [comment] 2017-09-29 16:59
Also see https://github.com/jhpoelen/effechecka/issues/56 .

**Comment by jhpoelen** [comment] 2017-09-29 17:15
I just confirmed that the supported URI (a URL is a kind of URI) length limit is 2048 (error message ```URI length exceeds the configured limit of 2048 characters```). So, while the api is configured with a much larger method length, the effective limit of the url length is 2048. Sorry for the confusion.

**Comment by BugwoodCenter** [comment] 2017-09-29 19:31
It is accepting either POST or GET for parameters?

**Comment by jhpoelen** [comment] 2017-09-29 19:37
Currently only GET. 

If we want to support large taxonSelectors, we'd have to also support POST, so you are not restricted by the url length limitation. Would you use POST if we'd add it?

**Comment by BugwoodCenter** [comment] 2017-09-29 19:44
I don't have a problem with POST - but how close do you want to stay to traditional REST where verbs have meaning?  I'm also fine with registering a list of taxa in a checklist.  If we added a new taxon i'd need to get archive data for just that taxon and then add them to the list but that's not horrible.  Granted, that means having expansion of the api for checklist CRUD.

Which poison is more palatable?  :)

**Comment by jhpoelen** [comment] 2017-09-29 19:58
Perhaps better to discuss by voice / chat - I want to make sure I understand your use case. @jhammock care to join?

**Comment by jhammock** [comment] 2017-09-29 20:06
go ahead without me; I'm still jumping from meeting to meeting

**Comment by jhpoelen** [comment] 2017-09-29 20:10
ok, @BugwoodCenter - let me know what works best for you

**Comment by BugwoodCenter** [comment] 2017-09-29 20:34
I'm new to GitHub - Not seeing a way to message you privately.  laforest@uga.edu e-mail be there with a phone number or google hangout address and a time and we'll chat.  I'll delete this after.

**Comment by jhpoelen** [comment] 2017-10-10 18:50
Hi @BugwoodCenter (and @diatomsRcool ) - I've implemented a first pass at http post support for checklist and occurrences . With this, you can make really big selectors without having to run into url length constraint. See docs at https://github.com/gimmefreshdata/freshdata/wiki/api#post-occurrences and https://github.com/gimmefreshdata/freshdata/wiki/api#post-checklist . 

Please let me know if this resolves your issue.

**Comment by jhpoelen** [comment] 2017-11-02 22:47
@BugwoodCenter @jhammock if this issue has been resolved, please close this issue. Otherwise, please describe what needs to be done.

**Comment by BugwoodCenter** [comment] 2017-11-16 20:39
I'll close this and if something goes wonky in testing i'll spawn an new issue.

**Closed as completed** 2017-11-16 20:39 UTC

**Comment by diatomsRcool** [comment] 2018-01-05 17:54
Will the POST method also work for long wkt strings? or is it just long selectors?

**Comment by BugwoodCenter** [comment] 2018-01-05 18:16
The wkt is part of the selector so i'd guess yes - but I do not know what validation is on the wkt.
