### ISSUE TITLE
search parameters are lost forever if we have an interrupt

### ISSUE THREAD

**Issue by jhammock** [gimmefreshdata/freshdata#40] opened 2016-07-08 22:07 UTC
I was about to instruct a test user to just click the link in an old notification email to reactivate a query after a possible server move related interrupt. That won't work, though, because the uuid -> query mappings are not saved. Is this a possible danger once we're out of testing phase, and if so, is there a clever way to address it?

**Comment by jhpoelen** [comment] 2016-07-25 22:28
This is a duplicate of #37 . Many ways to address this e.g. persist (parts of) query cache or perhaps even allow to export/save query parameters to data publication framework like zenodo. Also, please note that uuids are derived from the query parameters, so if a consuming platform like EOL saves its user queries, freshdata would generate identifical uuids regardless of whether the query existed before. Perhaps something to discuss by voice.

**Closed as completed by jhpoelen** 2016-07-25 22:28 UTC
