### ISSUE TITLE
hdfs (distributed file system) is unreachable, causing failures of effechecka, freshdata and more

### ISSUE THREAD

**Issue by jhammock** [gimmefreshdata/freshdata#85] opened 2018-10-29 14:39 UTC
I'm not sure if this is a GUODA or an effechecka issue,  eg: 

http://gimmefreshdata.github.io/?limit=20&taxonSelector=Aves%2CInsecta&traitSelector=&wktString=POLYGON%20%28%28-72.147216796875%2041.492120839687786%2C%20-72.147216796875%2043.11702412135048%2C%20-69.949951171875%2043.11702412135048%2C%20-69.949951171875%2041.492120839687786%2C%20-72.147216796875%2041.492120839687786%29%29

(or any other job, I think)

error: "[not ok. Received a [0:] status with message [] in response to ..."

**Comment by jhpoelen** [comment] 2018-10-29 15:06
@jhammock I renamed the issue, to reflect what I believe it the root cause of the inability for effechecka and gimmefreshdata to return results.

A misbehaving hdfs is consistent with what I just observed via a terminal on jupyter.guoda.bio -
```console
idb-jupyter1:~$ hdfs dfs -ls                                                                                              
2018-10-29 11:01:21,183 INFO  [main] retry.RetryInvocationHandler (RetryInvocationHandler.java:invoke(140)) - Exception while invok
ing getFileInfo of class ClientNamenodeProtocolTranslatorPB over mesos02.acis.ufl.edu/10.13.44.18:8020 after 1 fail over attempts. 
Trying to fail over after sleeping for 856ms.                                                                                      
org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.ipc.StandbyException): Operation category READ is not supported in state st
andby                                                                                                                              
        at org.apache.hadoop.hdfs.server.namenode.ha.StandbyState.checkOperation(StandbyState.java:87)                             
        at org.apache.hadoop.hdfs.server.namenode.NameNode$NameNodeHAContext.checkOperation(NameNode.java:1774)                    
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkOperation(FSNamesystem.java:1313)                              
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getFileInfo(FSNamesystem.java:3856)                                 
        at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getFileInfo(NameNodeRpcServer.java:1006)                       
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getFileInfo(ClientNamenodeProtocolServerS
ideTranslatorPB.java:843)                                                                                                          
        at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNam
enodeProtocolProtos.java)                                                                                                          
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:616)                      
        at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:969)                                                                     
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2049)                                                            
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2045)                                                            
        at java.security.AccessController.doPrivileged(Native Method)                                                              
        at javax.security.auth.Subject.doAs(Subject.java:422)                                                                      
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)                                    
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2043)
```

@mjcollin - can you confirm that hdfs is in a state that prevents reads from the cluster?

**Comment by jhpoelen** [comment] 2018-10-29 15:17
related to https://github.com/bio-guoda/guoda-services/issues/54 .

**Comment by mjcollin** [comment] 2018-10-29 15:53
Haven't read through the assortment of tickets this morning but HDFS had exited due to lack of memory on the primary name node, I upped the memory and restarted. Seems up now.

**Comment by jhammock** [comment] 2018-10-29 16:05
tried effechecka again. Some queries work!

Different problem:
"The occurrences you've requested contains no items. Bummer! You might want to try changing your search parameters. " when this is unlikely.

http://gimmefreshdata.github.io/?limit=20&monitorAPI=0&taxonSelector=&traitSelector=&uuid=&wktString=POLYGON%20%28%28-76.6900634765625%2038.77978137804918%2C%20-76.640625%2038.91240739487225%2C%20-77.19268798828125%2039.34916646551957%2C%20-77.4810791015625%2039.11301365149975%2C%20-77.32040405273436%2039.052784883296624%2C%20-77.54150390625%2038.85682013474361%2C%20-77.22152709960938%2038.65870536210694%2C%20-77.19818115234375%2038.62008939987629%2C%20-77.07046508789061%2038.61257832462118%2C%20-76.89468383789062%2038.649053322140226%2C%20-76.74774169921875%2038.62116234642254%2C%20-76.74156188964844%2038.561321083266414%2C%20-76.68113708496092%2038.541720956040386%2C%20-76.6900634765625%2038.77978137804918%29%29

**Comment by jhpoelen** [comment] 2018-10-29 16:17
@jhammock looks like hdfs is up but freshdata results are empty due to a failed FreshData updateAll. This is consistent with FreshData's updateAll crashing hdfs on updating, leaving the results empty until a successful updateAll occurs. 

@mjcollin please confirm that hdfs crashed on attempting to handle the many hdfs writes required by updateAll job of FreshData.

**Comment by jhpoelen** [comment] 2018-10-29 16:24
Am closing this issue, since the root cause of this issue has been resolved.  A new, more general issue has been opened on the instability of hdfs. https://github.com/bio-guoda/guoda-services/issues/57 .

**Comment by jhpoelen** [comment] 2019-03-08 17:42
HDFS appears to be having issues again. 

From logs today:
```
19-03-08 12:24:14 WARN RetryInvocationHandler: Exception while invoking class org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo over mesos01.acis.ufl.edu/10.13.44.15:8020. Not retrying because failovers (15) exceeded maximum allowed (15)
java.net.ConnectException: Call From mesos06/10.13.44.30 to mesos01.acis.ufl.edu:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at sun.reflect.GeneratedConstructorAccessor17.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:792)
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:732)
	at org.apache.hadoop.ipc.Client.call(Client.java:1480)
	at org.apache.hadoop.ipc.Client.call(Client.java:1413)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
```

**Closed as completed** 2019-03-20 17:51 UTC
