### ISSUE TITLE
access from google search

### ISSUE THREAD

**Issue by mxweber** [gimmefreshdata/freshdata#13] opened 2016-04-19 16:19 UTC
I tried a google search for gimme fresh data in safari on a new computer. I couldn't get a search page. The usual Boston example did not show. No option to enter my own data either. 

But the usual editable Boston example shows up on Chrome. Not sure if this is a known issue or not but I thought I would mention it. Feel free to contact me if you want to discuss.

-mxw

**Comment by jhpoelen** [comment] 2016-04-19 16:29
@mxweber interesting! I tried to replicate your issue on safari Version 9.1 (11601.5.17.1) (see screenshot) and the default search page does seem to appear. What version of safari are you using? 
![screen shot 2016-04-19 at 9 27 25 am](https://cloud.githubusercontent.com/assets/1084872/14647142/39fff248-0611-11e6-98bb-1ef4506ba077.png)

**Comment by mxweber** [comment] 2016-04-19 17:11
Version 9.1 as well. 

And yes, the image you posted is what I usually see on the usual front page. But I got this:
![gimmefd_ios9 1_safari](https://cloud.githubusercontent.com/assets/11161838/14648425/3e343472-0630-11e6-9723-c187ae03e507.png)

**Comment by jhpoelen** [comment] 2016-04-25 23:22
@mxweber I was unable to reproduce this issue. Please let me know how to reproduce this. Otherwise, please close the issue.

**Comment by jhpoelen** [comment] 2016-04-29 17:13
added extra info to the github repositories to be able to link to the prototype website. @mxweber please comment if issue re-occurs.

**Closed as completed by jhpoelen** 2016-04-29 17:13 UTC
