### ISSUE TITLE
newly added NEON data not found?

### ISSUE THREAD

**Issue by jhammock** [gimmefreshdata/freshdata#47] opened 2016-08-25 21:50 UTC
I would have expected this search

http://gimmefreshdata.github.io/?limit=20&taxonSelector=Aedes&traitSelector=&wktString=POLYGON%20%28%28-127.44140625%2030.14512718337613%2C%20-127.44140625%2049.49667452747045%2C%20-68.5546875%2049.49667452747045%2C%20-68.5546875%2030.14512718337613%2C%20-127.44140625%2030.14512718337613%29%29

To fetch some of the data provided by the newly added NEON resource, but it appears to contain no NEON records.

The NEON resource includes a number of Aedes species, with ancestry down to order, and no authority strings. Perhaps they are not found because they don't match well enough?

**Comment by jhpoelen** [comment] 2016-08-25 22:35
At close look of the neon archive as specified in https://github.com/gimmefreshdata/source-neon/blob/master/Jenkinsfile , I noticed that the file had DOS line endings (^M). However, in the meta.xml the line endings are specified as `\n` .  

I've attached a neon dwca with converted line endings. Please inspect and replace. 

[neonFixedLineEndings.zip](https://github.com/gimmefreshdata/freshdata/files/438177/neonFixedLineEndings.zip)

Confusingly, the archive validator succeeds . . . http://tools.gbif.org/dwca-reports/239-1584213064732219760.html .

**Comment by jhpoelen** [comment] 2016-08-25 23:18
On second thought. . . I looked at the resulting files, I found that the parsing succeeded ok, despite of the funny line endings.  Continuing to look for root cause.

**Comment by jhpoelen** [comment] 2016-08-26 00:03
Turns out that neon resources did not specify genus Aedes explicitly. Term scientific name was used to document the genus / species. 

Changed the taxon matching algorithm to match on names and words in names.

So, previously, scientific name `Aedes mitchellae` in occurrence record without explicit reference to genus `Aedes` did not match the `Aedes` taxon selector. 

Now, it does. Will trigger monitor update to refresh data. Will let you know when this is ready (see archive.effechecka.org for progress)

**Comment by jhammock** [comment] 2016-08-26 14:42
Ohh... I'm too used to ancestry for EOL resources. So, for Fresh Data resources, the search will rely only on ancestry in the resource itself? That's a basic thing for me not to know. At some point I will re load this resource with another rank or two if that's practical. Will check reef life survey also. But I will assume genus can be detected in the ScientificName column. Thanks!

**Comment by jhpoelen** [comment] 2016-08-26 16:10
Taxonomic linking can be added, and adds a new dimension to the monitoring. Doing things like: send me a notification if occurrences that link to NCBI, or send me a notification if occurrences don't link to anything . . . Perhaps an enhancement to keep in mind.

Also, I found another issue with neon dataset that prevented the propagation of the data. . . . the neon data was not linked properly into the fresh data archives. This issue has now been resolved and I have started a new monitor refresh. Will report back when changes have propagated.

**Comment by jhpoelen** [comment] 2016-08-29 15:53
Just now (2016-08-29), Neon data appeared in query added [since 2016-08-19](http://gimmefreshdata.github.io/?addedAfter=2016-08-19&limit=20&taxonSelector=Aedes&traitSelector=&wktString=POLYGON%20%28%28-127.44140625%2030.14512718337613%2C%20-127.44140625%2049.49667452747045%2C%20-68.5546875%2049.49667452747045%2C%20-68.5546875%2030.14512718337613%2C%20-127.44140625%2030.14512718337613%29%29) to [Aedes monitor](http://gimmefreshdata.github.io/?limit=20&taxonSelector=Aedes&traitSelector=&wktString=POLYGON%20%28%28-127.44140625%2030.14512718337613%2C%20-127.44140625%2049.49667452747045%2C%20-68.5546875%2049.49667452747045%2C%20-68.5546875%2030.14512718337613%2C%20-127.44140625%2030.14512718337613%29%29). Also see screenshot.

Closing issue. Please re-open / comment when issue (re-) appears.

![screen shot 2016-08-29 at 8 50 08 am](https://cloud.githubusercontent.com/assets/1084872/18057720/0444cf58-6dc6-11e6-8f37-e42512846662.png)

**Closed as completed by jhpoelen** 2016-08-29 15:53 UTC
Labels: bug
