### ISSUE TITLE
TSV download truncation is still in effect, only for queries without taxon filter

### ISSUE THREAD

**Issue by jhammock** [gimmefreshdata/freshdata#70] opened 2017-06-29 18:33 UTC
see for instance 

http://gimmefreshdata.github.io/?limit=20&taxonSelector=&traitSelector=&wktString=POLYGON%20%28%28-97.822265625%2018.312810846425442%2C%20-97.822265625%2031.05293398570514%2C%20-80.595703125%2031.05293398570514%2C%20-80.595703125%2018.312810846425442%2C%20-97.822265625%2018.312810846425442%29%29

(All queries with taxon filters which I have tried download complete TSV)

**Comment by jhpoelen** [comment] 2017-07-07 21:52
Was able to reproduce and fix the issue. Turned out that empty taxon names the root cause.

Please confirm that the issue has been resolved by closing this issue.

**Comment by jhammock** [comment] 2017-08-02 17:31
I believe this is fixed for occurrence queries but persists for checklist queries, see example:
(widgetized for convenience)

http://gimmefreshdata.github.io/?limit=5000000&taxonSelector=&traitSelector=&wktString=GEOMETRYCOLLECTION%28POLYGON%20%28%28-65.022%2063.392%2C%20-74.232%2064.672%2C%20-84.915%2071.353%2C%20-68.482%2068.795%2C%20-67.685%2066.286%2C%20-65.022%2063.392%29%29%2CPOLYGON%20%28%28-123.126%2049.079%2C%20-129.911%2053.771%2C%20-125.34%2069.52%2C%20-97.874%2068.532%2C%20-85.754%2068.217%2C%20-91.525%2063.582%2C%20-77.684%2060.542%2C%20-64.072%2059.817%2C%20-55.85%2053.249%2C%20-64.912%2043.79%2C%20-123.126%2049.079%29%29%29
TSV service for this query is fine

http://www.effechecka.org/?limit=5000000&taxonSelector=&traitSelector=&wktString=GEOMETRYCOLLECTION%28POLYGON%20%28%28-65.022%2063.392%2C%20-74.232%2064.672%2C%20-84.915%2071.353%2C%20-68.482%2068.795%2C%20-67.685%2066.286%2C%20-65.022%2063.392%29%29%2CPOLYGON%20%28%28-123.126%2049.079%2C%20-129.911%2053.771%2C%20-125.34%2069.52%2C%20-97.874%2068.532%2C%20-85.754%2068.217%2C%20-91.525%2063.582%2C%20-77.684%2060.542%2C%20-64.072%2059.817%2C%20-55.85%2053.249%2C%20-64.912%2043.79%2C%20-123.126%2049.079%29%29%29
This, the checklist version, is truncated

http://www.effechecka.org/?limit=5000000&taxonSelector=Aves%2CInsecta&traitSelector=&wktString=GEOMETRYCOLLECTION%28POLYGON%20%28%28-65.022%2063.392%2C%20-74.232%2064.672%2C%20-84.915%2071.353%2C%20-68.482%2068.795%2C%20-67.685%2066.286%2C%20-65.022%2063.392%29%29%2CPOLYGON%20%28%28-123.126%2049.079%2C%20-129.911%2053.771%2C%20-125.34%2069.52%2C%20-97.874%2068.532%2C%20-85.754%2068.217%2C%20-91.525%2063.582%2C%20-77.684%2060.542%2C%20-64.072%2059.817%2C%20-55.85%2053.249%2C%20-64.912%2043.79%2C%20-123.126%2049.079%29%29%29
The checklist version with a taxon filter, is also fine

**Comment by jhammock** [comment] 2017-09-15 16:31
Hmm... Did someone start to work on this? The behavior is different now. Fresh example below just in case, but the original example behaves the same. Now, The occurrence query without taxon filter still succeeds, the corresponding checklist with a taxon filter added still succeeds, but the corresponding checklist without taxon filter throws an error for TSV download: "Failed - Network error"

New example:

occurrence query without taxon filter
http://gimmefreshdata.github.io/?limit=20&taxonSelector=&traitSelector=&wktString=POLYGON%20%28%28-78.343505859375%2038.36736756347068%2C%20-78.343505859375%2039.56322082837927%2C%20-76.278076171875%2039.56322082837927%2C%20-76.278076171875%2038.36736756347068%2C%20-78.343505859375%2038.36736756347068%29%29

corresponding checklist with a taxon filter added
http://www.effechecka.org/?limit=20&taxonSelector=Aves%2CInsecta&traitSelector=&wktString=POLYGON%20%28%28-78.343505859375%2038.36736756347068%2C%20-78.343505859375%2039.56322082837927%2C%20-76.278076171875%2039.56322082837927%2C%20-76.278076171875%2038.36736756347068%2C%20-78.343505859375%2038.36736756347068%29%29

corresponding checklist without taxon filter
http://www.effechecka.org/?limit=20&taxonSelector=&traitSelector=&wktString=POLYGON%20%28%28-78.343505859375%2038.36736756347068%2C%20-78.343505859375%2039.56322082837927%2C%20-76.278076171875%2039.56322082837927%2C%20-76.278076171875%2038.36736756347068%2C%20-78.343505859375%2038.36736756347068%29%29

**Comment by jhpoelen** [comment] 2017-09-22 16:10
The suspected truncated checklist is associated with hdfs path ```/guoda/data/monitor/checklist/u0=8b/u1=cc/u2=02/uuid=8bcc0261-f885-5f36-ab7a-4e72ef2e0b82/checklist.parquet```. According to spark, the checklist contains about 26k rows (see log from jupyter terminal spark session below)

```scala
scala> val cl = spark.read.parquet("/guoda/data/monitor/checklist/u0=8b/u1=cc/u2=02/uuid=8bcc0261-f885-5f36-ab7a-4e72ef2e0b82/checklist.parquet")                                                                                                                     
cl: org.apache.spark.sql.DataFrame = [taxonPath: string, recordCount: bigint]                                                      
                                                                                                                                   
scala> cl.head                                                                                                                     
res2: org.apache.spark.sql.Row = [Animalia|Chordata|Aves|Passeriformes|Cardinalidae|Cardinalis|cardinalis|Cardinalis cardinalis (Li
nnaeus, 1758),386961]                                                                                                              
                                                                                                                                   
scala> cl.count                                                                                                                    
res3: Long = 26163    
```

**Comment by jhpoelen** [comment] 2017-09-22 16:44
When accessing a tsv checklist (see 
[checklist-8bcc0261-f885-5f36-ab7a-4e72ef2e0b82-20170922.txt](https://github.com/gimmefreshdata/freshdata/files/1325237/checklist-8bcc0261-f885-5f36-ab7a-4e72ef2e0b82-20170922.txt))
 from http://www.effechecka.org/?limit=20&taxonSelector=&traitSelector=&wktString=POLYGON%20%28%28-78.343505859375%2038.36736756347068%2C%20-78.343505859375%2039.56322082837927%2C%20-76.278076171875%2039.56322082837927%2C%20-76.278076171875%2038.36736756347068%2C%20-78.343505859375%2038.36736756347068%29%29 with uuid 8bcc0261-f885-5f36-ab7a-4e72ef2e0b82 it appears that only 269 lines items were provided instead of the expected 26k.

**Comment by jhpoelen** [comment] 2017-09-22 17:46
I found, reproduced and fixed the issue. Also, I've deployed the changes and downloaded checklist with expected 26k items (see 
[checklist-8bcc0261-f885-5f36-ab7a-4e72ef2e0b82-20170922-fixed.txt](https://github.com/gimmefreshdata/freshdata/files/1325366/checklist-8bcc0261-f885-5f36-ab7a-4e72ef2e0b82-20170922-fixed.txt))
. 

@jhammock please confirm by closing this issue.

**Comment by jhpoelen** [comment] 2017-09-22 17:49
PS The reason why this only happened without taxon filters is that only empty taxon paths (occurrences with no taxonomic information) caused the download interruption.

**Comment by diatomsRcool** [comment] 2017-09-25 17:49
Here's one that is not working
http://api.effechecka.org/checklist?limit=5000000&traitSelector=&wktString=POLYGON((21.401%2069.287%2C%2022.807%2068.672%2C%2024.916%2068.608%2C%2026.367%2069.9%2C%2027.685%2070.02%2C%2029.003%2069.626%2C%2028.388%2068.496%2C%2029.794%2067.609%2C%2029.003%2066.895%2C%2029.97%2065.802%2C%2030.146%2064.014%2C%2031.464%2062.915%2C%2027.509%2060.413%2C%2026.059%2060.02%2C%2021.313%2059.489%2C%2020.83%2060.951%2C%2020.522%2063.213%2C%2023.027%2064.148%2C%2024.653%2065.33%2C%2023.642%2066.425%2C%2023.466%2067.958%2C%2020.742%2069.052%2C%2021.401%2069.287))

Only getting about a dozen birds. That doesn't seem right for Finland.

**Comment by jhpoelen** [comment] 2017-09-25 18:10
Thanks for pointing this out. In a (somewhat) recent effechecka api change, we decided to use json responses only for summaries (top 20). To get the full list tsv files should be requested. 

So, you should get the full list if you add ".tsv" to the link you shared (e.g., http://api.effechecka.org/checklist.tsv?traitSelector=&wktString=POLYGON((21.401%2069.287%2C%2022.807%2068.672%2C%2024.916%2068.608%2C%2026.367%2069.9%2C%2027.685%2070.02%2C%2029.003%2069.626%2C%2028.388%2068.496%2C%2029.794%2067.609%2C%2029.003%2066.895%2C%2029.97%2065.802%2C%2030.146%2064.014%2C%2031.464%2062.915%2C%2027.509%2060.413%2C%2026.059%2060.02%2C%2021.313%2059.489%2C%2020.83%2060.951%2C%2020.522%2063.213%2C%2023.027%2064.148%2C%2024.653%2065.33%2C%2023.642%2066.425%2C%2023.466%2067.958%2C%2020.742%2069.052%2C%2021.401%2069.287)) ) .

This behavior is documented https://github.com/gimmefreshdata/freshdata/wiki/api#checklist and https://github.com/gimmefreshdata/freshdata/wiki/api#checklisttsv . If you have any suggestion to make this a little more intuitive, please holler.

**Comment by jhammock** [comment] 2017-09-25 18:15
Oops, I should have remembered that myself- sorry. 31,000 mixed taxa; that looks like a reasonable result. @diatomsRcool , how does Brazil turn out w/.tsv?

**Comment by diatomsRcool** [comment] 2017-09-25 20:16
Now I'm getting at HTTP 400
My guess is I have to rewrite my code to accommodate the tsv format, but I can't do it right now

**Comment by jhpoelen** [comment] 2017-09-25 20:34
Just tried the tsv url, and I was able to get data from it, so got http code 200. Which url did you use?

**Comment by jhpoelen** [comment] 2017-09-25 20:38
btw - tsv format is suitable from streaming large amounts of data, json not so much.

Also note that leaving out the ```limit``` parameter will return all results, so there's no need to do things like ```limit=50000000``` if you are interested in getting all data.

Let me know how I can help move your project along.

**Comment by diatomsRcool** [comment] 2017-09-25 23:06
I got it working. Thanks!

**Closed as completed** 2017-09-26 14:28 UTC
