### ISSUE TITLE
website issues?

### ISSUE THREAD

**Issue by turnerh** [gimmefreshdata/freshdata#83] opened 2018-02-12 07:44 UTC
I did a search yesterday for occurrences of taxa, and just kept getting a ‘busy’ response each time I reloaded the webpage. I assumed that the search had stalled, so opened a new window (even restarted my browser first) and tried the same search, but now I keep getting error messages.

The URL is 
http://gimmefreshdata.github.io/?limit=20&taxonSelector=Sararanga&traitSelector=&wktString=GEOMETRYCOLLECTION%28POLYGON%20%28%28-180%20-43%2C%20-180%2029%2C%20-139%2029%2C%20-139%20-43%2C%20-180%20-43%29%29%2CPOLYGON%20%28%2875%20-43%2C%2075%2029%2C%20180%2029%2C%20180%20-43%2C%2075%20-43%29%29%29

and the response is

occurrences status: [not ok. Received a [0:] status with message [] in response to [http://api.effechecka.org/occurrences?limit=20&taxonSelector=Sararanga&wktString=GEOMETRYCOLLECTION(POLYGON%20((-180%20-43%2C%20-180%2029%2C%20-139%2029%2C%20-139%20-43%2C%20-180%20-43))%2CPOLYGON%20((75%20-43%2C%2075%2029%2C%20180%2029%2C%20180%20-43%2C%2075%20-43)))]] ?

It doesn’t matter which taxon I ask for in the taxonSelector. (Actually, I searched other taxa and this particular was run successfully before.)
Are there issues again with the server?

**Comment by mjcollin** [comment] 2018-02-12 13:40
I had stopped the API to work on HDFS, see https://github.com/bio-guoda/guoda-services/issues/45

I don't have a contact email address for you, Jorrit gave me one but I keep getting failed deliveries. I had sent an email around to other users announcing this work. Could you email me directly so I can add you to that list? mcollins at acis.ufl.edu

**Comment by jhpoelen** [comment] 2018-10-29 15:07
duplicate of #85 , closing issue.

**Closed as completed** 2018-10-29 15:07 UTC
