### ISSUE TITLE
Freshdata search results include non-research grade iNat data

### ISSUE THREAD

**Issue by yrhe** [gimmefreshdata/freshdata#12] opened 2016-03-24 02:42 UTC
When I searched "Dermaptera" on Fresh Data, not all the iNat data under "occurrence id" were research grade. 

The screenshot for part of the searching result on Fresh Data:

<img width="1218" alt="screen shot 2016-03-23 at 10 26 25 pm" src="https://cloud.githubusercontent.com/assets/15819985/14006697/60394688-f146-11e5-97c6-f6a9e359073b.png">

For the first iNat data: http://www.inaturalist.org/observations/264943, it reaches "research" grade. 

The screenshot for this research grade data:
<img width="758" alt="screen shot 2016-03-23 at 10 29 39 pm" src="https://cloud.githubusercontent.com/assets/15819985/14006768/112bb6d8-f147-11e5-8826-78d8321c34b0.png">

But for the the second iNat data: http://www.inaturalist.org/observations/265402, it only reaches "needs id" grade. 

The screenshot for this needs id grade data:
<img width="748" alt="screen shot 2016-03-23 at 10 35 14 pm" src="https://cloud.githubusercontent.com/assets/15819985/14006857/cf185aa2-f147-11e5-87d0-f2a5ea42b7f7.png">

According to today's group meeting, we know that iNat data displayed on Fresh Data are from GBIF, not from EOL (please correct me if I remembered this wrong), and supposed to be research grade.

**Comment by yrhe** [comment] 2016-03-24 02:53
@jhpoelen , sorry I did not saw your already opened this issue so I created one by myself. I tried to delete this one created by myself, but did not find the "delete" button, could you please help to delete it? Thanks!

**Comment by jhpoelen** [comment] 2016-03-24 05:06
closing issue, duplicate of #8

**Closed as completed by jhpoelen** 2016-03-24 05:06 UTC

**Comment by yrhe** [comment] 2016-03-24 13:03
Thank you, Jorrit!
